In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
movies = pd.read_csv("datasets/tmdb_5000_movies.csv")
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [3]:
credit = pd.read_csv("datasets/tmdb_5000_credits.csv")
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
movies.shape

(4803, 20)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [7]:
movies.isnull().any(axis=1).sum()

3310

In [8]:
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.shape

(4803, 20)

In [10]:
movies = movies.merge(credit,on="title")

In [11]:
movies.shape

(4809, 23)

In [12]:
movies.shape[1]

23

In [13]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
# columns to keep - genres,id,keywords,overview,title,cast,crew
final_movies = movies[["id","title","overview","genres","keywords","cast","crew"]]

In [15]:
final_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [16]:
final_movies[final_movies["overview"].isnull()]

,id,title,overview,genres,keywords,cast,crew
2662,370980,Chiamatemi Francesco - Il Papa della gente,NaN,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 717, ""name"": ""pope""}, {""id"": 5565, ""na...","[{""cast_id"": 5, ""character"": ""Jorge Mario Berg...","[{""credit_id"": ""5660019ac3a36875f100252b"", ""de..."
4147,459488,"To Be Frank, Sinatra at 100",NaN,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 6027, ""name"": ""music""}, {""id"": 225822,...","[{""cast_id"": 0, ""character"": ""Narrator"", ""cred...","[{""credit_id"": ""592b25e4c3a368783e065a2f"", ""de..."
4437,292539,Food Chains,NaN,"[{""id"": 99, ""name"": ""Documentary""}]",[],[],"[{""credit_id"": ""5470c3b1c3a368085e000abd"", ""de..."

In [17]:
final_movies.dropna(inplace=True)

C:\Users\Naman\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [18]:
final_movies.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [19]:
final_movies.duplicated().sum()

0

In [20]:
final_movies.head(1)["genres"].values

array(['[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'],
      dtype=object)

In [21]:
import json

In [22]:
final_movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [23]:
final_movies["keywords"].apply(lambda x:[d["name"] for d in json.loads(x)])

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [24]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [25]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L

In [26]:
final_movies["genres"] = final_movies["genres"].apply(convert)
final_movies.head()

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/4114556549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_movies["genres"] = final_movies["genres"].apply(convert)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
final_movies["keywords"]=final_movies["keywords"].apply(convert)
final_movies.head(1)

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/1526766632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_movies["keywords"]=final_movies["keywords"].apply(convert)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [28]:
def convert1(obj):
    L = []
    x = 0
    for i in ast.literal_eval(obj):
        if x < 3:
            x+=1
            L.append(i["name"])
        else:
            break
    return L

In [29]:
final_movies["cast"] = final_movies["cast"].apply(convert1)

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/2535737466.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_movies["cast"] = final_movies["cast"].apply(convert1)

In [30]:
final_movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [31]:
final_movies["director"] = final_movies["crew"].apply(lambda x: [i["name"] for i in ast.literal_eval(x) if i["job"] == "director"])

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/3827265949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_movies["director"] = final_movies["crew"].apply(lambda x: [i["name"] for i in ast.literal_eval(x) if i["job"] == "director"])

In [32]:
final_movies.drop(axis=0,columns="director",inplace=True)

C:\Users\Naman\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [33]:
final_movies

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [34]:
final_movies["Director"] = final_movies["crew"].apply(lambda x: [i["name"] for i in json.loads(x) if i["job"] == "Director"])

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/3428354947.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_movies["Director"] = final_movies["crew"].apply(lambda x: [i["name"] for i in json.loads(x) if i["job"] == "Director"])

In [35]:
final_movies.drop(axis=0,columns="crew",inplace=True)

C:\Users\Naman\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [36]:
final_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4806 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4806 non-null   int64
 1   title     4806 non-null   object
 2   overview  4806 non-null   object
 3   genres    4806 non-null   object
 4   keywords  4806 non-null   object
 5   cast      4806 non-null   object
 6   Director  4806 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.4+ KB

In [37]:
final_movies["overview"] = final_movies["overview"].apply(lambda x: x.split(" "))

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/4081094755.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_movies["overview"] = final_movies["overview"].apply(lambda x: x.split(" "))

In [38]:
final_movies.head(5)

,id,title,overview,genres,keywords,cast,Director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [39]:
final_movies[["genres","keywords","cast","Director"]] = final_movies[["genres","keywords","cast","Director"]].applymap(lambda x: [i.replace(" ","") for i in x])

C:\Users\Naman\anaconda3\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [40]:
final_movies

,id,title,overview,genres,keywords,cast,Director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]"

In [41]:
final_movies["tags"] = final_movies["overview"]+final_movies["genres"]+final_movies["keywords"]+final_movies["cast"]+final_movies["Director"]

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/3919023162.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_movies["tags"] = final_movies["overview"]+final_movies["genres"]+final_movies["keywords"]+final_movies["cast"]+final_movies["Director"]

In [42]:
new_df = final_movies[["id","title","tags"]]

In [43]:
new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/3719869087.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))

In [44]:
new_df

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [45]:
new_df["tags"] = new_df["tags"].apply(lambda x: x.lower())

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/1654334444.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x: x.lower())

In [46]:
new_df.head(5)

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

## Modelling

Now data is preprocessed now we have to do text vectorization where we convert text into vectors.
method for doing so:

### 1️⃣ Basic Method

1) Bag of Words-
* Converts text into a frequency-based representation.
* Ignores the order of words.
* 

``` 
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["I love NLP and AI", "AI loves me"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())  # Vocabulary
print(X.toarray())  # Vectorized text
```

2) TF-IDF (Term Frequency-Inverse Document Frequency)
* Adjusts word frequency by penalizing common words.
* Helps reduce bias towards frequently occurring words.
* 

```
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = ["I love NLP and AI", "AI loves me"]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())

```

### 2️⃣ Word Embeddings (Dense Representations)
Unlike BoW or TF-IDF, embeddings capture meaning and relationships between words.

1) Word2Vec (Using gensim)
* Converts words into dense vectors based on their usage in large corpora.
* Two approaches: CBOW (Continuous Bag of Words) and Skip-gram.
```
from gensim.models import Word2Vec

sentences = [["I", "love", "NLP"], ["AI", "loves", "me"], ["Machine", "learning", "is", "fun"]]
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

print(model.wv["love"])  # Vector for "love"
```

2) FastText (Word2Vec but better)
* Captures subword information (useful for handling rare words or misspellings).
* Example: "running" = ["run", "unning"] → better generalization.
```
from gensim.models import FastText

model = FastText(sentences, vector_size=100, window=5, min_count=1, workers=4)
print(model.wv["love"])  # Vector for "love"
```
3) GloVe (Global Vectors)
* Pre-trained embeddings trained on word co-occurrence.
* Available for different corpus sizes (e.g., Wikipedia, Common Crawl).
```
import gensim.downloader as api

glove_vectors = api.load("glove-wiki-gigaword-100")  # Load pre-trained GloVe 100D vectors
print(glove_vectors["love"])  # Vector for "love"
```
### 3️⃣ Contextualized Embeddings (Deep Learning)
Unlike Word2Vec, these models generate different vector representations for words based on context.

1) BERT (Bidirectional Encoder Representations from Transformers)
* Uses transformers to capture context dynamically.
* Produces different vectors for "bank" in:
"I deposited money in the bank."
"I sat near the river bank."
```
from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

text = "I love NLP and AI"
inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)

print(outputs.last_hidden_state.shape)  # Token-wise embeddings
```
### 🚀 Summary: Best Approach for Your Use Case

| Method | Use Case |
|:----------:|:----------:|
| BoW    | Simple ML models, small datasets   |
| TF-IDF    | Document classification, keyword extraction   |
| Word2Vec/FastText	|NLP tasks like sentiment analysis recommendation|
|GloVe|	General NLP tasks pre-trained vector usage|
|BERT	|Context-sensitive NLP (chatbots, question answering)|

### 🔗 Resources to Learn More
* Text Vectorization Guide: Scikit-learn Documentation
* Word Embeddings: Gensim Word2Vec Tutorial
* BERT Implementation: Hugging Face Transformers

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
cv = CountVectorizer(max_features = 5000, stop_words = "english")

In [49]:
vectors = cv.fit_transform(new_df["tags"]).toarray()

In [50]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'ann',
 'anna',
 'annabelle',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'anonymous',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'atlantic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breast',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colombia',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 ...]

# 🔹 NLTK (Natural Language Toolkit)
**NLTK** is one of the most popular libraries in Python for working with text data. It provides tools for:
- ✅ Tokenization  
- ✅ Stemming & Lemmatization  
- ✅ Stopword Removal  
- ✅ POS Tagging & Named Entity Recognition  
- ✅ Sentiment Analysis  

---

### 🔗 Installation
To install NLTK, run:
```bash
pip install nltk

import nltk
nltk.download('all')  # Downloads all necessary datasets
```

## 1️⃣ Tokenization (Splitting Text)
Tokenization breaks text into words or sentences.

```
from nltk.tokenize import word_tokenize, sent_tokenize

text = "I love NLP! It's amazing."
print(word_tokenize(text))  # ['I', 'love', 'NLP', '!', "It's", 'amazing', '.']
print(sent_tokenize(text))  # ['I love NLP!', "It's amazing."]
```
🔹 Use Case: Preparing text for NLP models.

## 2️⃣ Removing Stopwords
Stopwords are common words like "the", "is", "and", which add little meaning.

```
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))
words = word_tokenize("This is an amazing NLP tutorial!")
filtered_words = [word for word in words if word.lower() not in stop_words]

print(filtered_words)  # ['amazing', 'NLP', 'tutorial', '!']
```
🔹 Use Case: Reducing noise in text data.

## 3️⃣ Stemming (Reducing Words to Their Root)
Stemming reduces words to their base form.

```
from nltk.stem import PorterStemmer

ps = PorterStemmer()
print(ps.stem("running"))  # run
print(ps.stem("flies"))  # fli
```
🔹 Use Case: Search engines & text normalization.

## 4️⃣ Lemmatization (Better than Stemming)
Lemmatization reduces words to their base form using dictionary meanings.

```
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

print(lemmatizer.lemmatize("running", pos="v"))  # run
print(lemmatizer.lemmatize("better", pos="a"))  # good
```
🔹 Use Case: More accurate NLP models.

## 5️⃣ Part-of-Speech (POS) Tagging
Assigns grammatical categories (noun, verb, adjective, etc.).

```
from nltk import pos_tag

words = word_tokenize("I love deep learning.")
nltk.download('averaged_perceptron_tagger')
print(pos_tag(words))

Output:
[('I', 'PRP'), ('love', 'VBP'), ('deep', 'JJ'), ('learning', 'NN'), ('.', '.')]
```
🔹 Use Case: Named Entity Recognition (NER), grammar checking.

## 6️⃣ Named Entity Recognition (NER)
Identifies names, places, dates, and other entities.

```
from nltk.chunk import ne_chunk

nltk.download('maxent_ne_chunker')
nltk.download('words')

sentence = "Elon Musk founded SpaceX in California."
words = word_tokenize(sentence)
tags = pos_tag(words)
ner_tree = ne_chunk(tags)

print(ner_tree)
```
🔹 Use Case: Extracting company names, people, locations.

## 7️⃣ Sentiment Analysis
Classifies text as positive, negative, or neutral.

```
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()

print(sia.polarity_scores("I love this product!"))  # {'neg': 0.0, 'neu': 0.25, 'pos': 0.75, 'compound': 0.6369}
print(sia.polarity_scores("This is the worst thing ever!"))  # {'neg': 0.654, 'neu': 0.346, 'pos': 0.0, 'compound': -0.8271}
```
🔹 Use Case: Analyzing reviews, social media sentiment.

In [52]:
new_df["tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [53]:
new_df["tags"][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [54]:
new_df["tags"][2]

'a cryptic message from bond’s past sends him on a trail to uncover a sinister organization. while m battles political forces to keep the secret service alive, bond peels back the layers of deceit to reveal the terrible truth behind spectre. action adventure crime spy basedonnovel secretagent sequel mi6 britishsecretservice unitedkingdom danielcraig christophwaltz léaseydoux sammendes'

In [55]:
import nltk

In [56]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [57]:
ps.stem("loved")

'love'

In [58]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [59]:
new_df["tags"] = new_df["tags"].apply(lambda x:stem(x))

C:\Users\Naman\AppData\Local\Temp/ipykernel_137132/985053973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x:stem(x))

In [60]:
vectors1 = cv.fit_transform(new_df["tags"]).toarray()

In [61]:
vectors1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [62]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 ...]

In [63]:
from sklearn.metrics.pairwise import cosine_similarity

In [64]:
similarity = cosine_similarity(vectors1)

## Rock Paper Scissors

In [65]:
def winner(comp,person):
    if(comp == "Rock" and person=="paper"):
        return "You"
    elif (comp == "Rock" and person=="Scissors"):
        return "Computer"
    elif (comp == "paper" and person=="Rocks"):
        return "Computer"
    elif (comp == "paper" and person=="Scissors"):
        return "You"
    elif (comp == "Scissors" and person=="paper"):
        return "Computer"
    elif (comp == "Scissors" and person=="Rock"):
        return "You"
    else:
        return "Tie"

def ShowR(W,L,T):
    print(f"Your Score : wins : {W}, losses : {L}, Ties : {T}\n")

import random

option = {0:"Rock",1:"Paper",2:"Scissors"}

turns = 3

win = 0
loss = 0
tie = 0

ShowR(win,loss,tie)

print(f"You have {turns} games left\n")

while turns:
    
    Person = option[int(input("Enter your Choice (Rock:0, Paper:1,Scissors:2) : "))]
    Computer = option[random.randint(0,2)]
    
    result = winner(Computer,Person)
    
    if result == "You":
        win+=1
    elif result == "Computer":
        loss+=1
    else:
        tie+=1
    turns-=1
    
    ShowR(win,loss,tie)

Your Score : wins : 0, losses : 0, Ties : 0

You have 3 games left

Enter your Choice (Rock:0, Paper:1,Scissors:2) : 1
Your Score : wins : 0, losses : 0, Ties : 1

Enter your Choice (Rock:0, Paper:1,Scissors:2) : 2
Your Score : wins : 0, losses : 1, Ties : 1

Enter your Choice (Rock:0, Paper:1,Scissors:2) : 0
Your Score : wins : 1, losses : 1, Ties : 1

## continuation

In [66]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [67]:
sorted(list(enumerate(similarity[0])),reverse=True, key=lambda x:x[1])

[(0, 1.0000000000000002),
 (1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574),
 (582, 0.24511108480187255),
 (1204, 0.24455799402225922),
 (1194, 0.23179316248638276),
 (778, 0.23174488732966075),
 (4048, 0.2278389747471728),
 (1920, 0.2252817784447915),
 (61, 0.22269966704152225),
 (2786, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2333, 0.20443988269091456),
 (3608, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4192, 0.2029530274475215),
 (1444, 0.20277677641345318),
 (74, 0.2024645717996314),
 (1089, 0.2020475485519274),
 (3675, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2971, 0.19252140716412977),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1201, 0.19088542889273336),
 (305, 0.19007487139298027),
 (4, 0.1892994097121204),
 (4405, 0.18731716231633883),
 (94, 0.1873171623163388),
 (27, 0.18693292157876878),
 (3327, 0.1860807318911967),
 (1275, 0.18394180184548975),
 (1329, 0.18394180184548975),
 (2999, 0.1813690625275029),
 (3999, 0.18074256993863339),
 (83, 0.17996850826633903),
 (1071, 0.17954621161490197),
 (220, 0.1777046633277277),
 (1321, 0.17699808135119718),
 (168, 0.17521916101261562),
 (184, 0.17521916101261562),
 (2204, 0.17521916101261562),
 (4336, 0.17521916101261562),
 (931, 0.1748149640244195),
 (373, 0.17292861596651865),
 (300, 0.1711905958155815),
 (3538, 0.1711905958155815),
 (36, 0.17119059581558146),
 (3162, 0.17040572913692198),
 (1982, 0.16943474841747155),
 (529, 0.16742770563222897),
 (1831, 0.16742770563222897),
 (91, 0.16692446522239718),
 (661, 0.1661625969589056),
 (41, 0.16563698349810535),
 (150, 0.16426202236672155),
 (1537, 0.16222142113076254),
 (67, 0.16222142113076252),
 (342, 0.16122923187750418),
 (595, 0.16059101370939324),
 (31, 0.15907119074394446),
 (2515, 0.15907119074394446),
 (1178, 0.15789473684210528),
 (4010, 0.15737789507292674),
 (2731, 0.15609763526361567),
 (149, 0.15511334686589626),
 (838, 0.1540171257313038),
 (26, 0.15389675281277312),
 (187, 0.15389675281277312),
 (1344, 0.152008377581442),
 (1383, 0.152008377581442),
 (111, 0.15018785229652767),
 (311, 0.15018785229652765),
 (513, 0.14843120879858804),
 (2075, 0.14808721943977307),
 (7, 0.14673479641335554),
 (52, 0.14673479641335554),
 (2760, 0.14659886790209342),
 (127, 0.14601068654819693),
 (579, 0.14567913668701626),
 (581, 0.14567913668701626),
 (108, 0.14509525002200235),
 (1297, 0.14509525002200235),
 (466, 0.14509525002200233),
 (1396, 0.14421498760030763),
 (1479, 0.1442149876003076),
 (1355, 0.14350946197048198),
 (1938, 0.14350946197048198),
 (275, 0.1433848336691011),
 (294, 0.1433848336691011),
 (3354, 0.1433848336691011),
 (1056, 0.1419745572840903),
 (1273, 0.1419745572840903),
 (490, 0.14159846508095775),
 (1488, 0.14159846508095775),
 (413, 0.1411956236812263),
 (461, 0.1411956236812263),
 (568, 0.1411956236812263),
 (2496, 0.1411956236812263),
 (95, 0.14048787173725413),
 (17, 0.13977653617040256),
 (46, 0.1391037210186643),
 (3409, 0.1391037210186643),
 (1965, 0.13872950617564817),
 (56, 0.13834289277321493),
 (249, 0.13834289277321493),
 (1327, 0.13834289277321493),
 (3781, 0.13834289277321493),
 (72, 0.13710212427677043),
 (859, 0.13710212427677043),
 (2169, 0.13710212427677043),
 (4538, 0.13629325512727639),
 (476, 0.13530201829834768),
 (505, 0.13530201829834768),
 (668, 0.13530201829834768),
 (935, 0.13530201829834768),
 (3982, 0.13530201829834768),
 (843, 0.13518451760896877),
 (1808, 0.13518451760896877),
 (502, 0.13497638119975428),
 (4348, 0.13497638119975428),
 (1322, 0.13476498501489081),
 (158, 0.13369695534647594),
 (777, 0.13369695534647594),
 (126, 0.13334518676566626),
 (1560, 0.13334518676566626),
 (1373, 0.1324532357065044),
 (2378, 0.1324532357065044),
 (2584, 0.1324532357065044),
 (4079, 0.13157894736842107),
 (2133, 0.13124359177794215),
 (1015, 0.12988108336653278),
 (2181, 0.12988108336653278),
 (3622, 0.12988108336653278),
 (134, 0.12977713690461004),
 (368, 0.12977713690461004),
 (1774, 0.12977713690461004),
 (2873, 0.12892051277806202),
 (14, 0.12824729401064427),
 (138, 0.12824729401064427),
 (1086, 0.12824729401064427),
 (2686, 0.12824729401064427),
 (4230, 0.12824729401064427),
 (487, 0.12725695259515557),
 (773, 0.12725695259515557),
 (2970, 0.12725695259515557),
 (369, 0.126673647984535),
 (937, 0.126673647984535),
 (1741, 0.12565617248750865),
 (2480, 0.12565617248750865),
 (166, 0.12515654358043973),
 (754, 0.12515654358043973),
 (2450, 0.12515654358043973),
 (3628, 0.12515654358043973),
 (483, 0.12487810821089254),
 (1096, 0.12487810821089254),
 (1158, 0.12487810821089254),
 (102, 0.12462194771917919),
 (84, 0.12361284651454937),
 (208, 0.12262786789699316),
 (1301, 0.12262786789699316),
 (2652, 0.12262786789699316),
 (3376, 0.12262786789699316),
 (1878, 0.12262786789699313),
 (438, 0.12227899701112963),
 (557, 0.12227899701112963),
 (1299, 0.12227899701112963),
 (2331, 0.12166606584807191),
 (2674, 0.12166606584807191),
 (3083, 0.12166606584807191),
 (139, 0.12072654548783007),
 (68, 0.1204950466257556),
 (781, 0.1204950466257556),
 (1004, 0.1204950466257556),
 (1274, 0.1204950466257556),
 (1658, 0.1204950466257556),
 (1002, 0.11980845957463077),
 (549, 0.11959121830873498),
 (870, 0.11959121830873498),
 (900, 0.11959121830873498),
 (3235, 0.11959121830873498),
 (122, 0.11846977555181847),
 (1047, 0.11846977555181847),
 (1833, 0.11846977555181847),
 (2060, 0.11846977555181847),
 (2741, 0.11846977555181847),
 (4673, 0.11846977555181847),
 (1617, 0.11831213107007527),
 (3721, 0.11803342130469506),
 (1673, 0.11803342130469505),
 (1715, 0.11803342130469505),
 (2789, 0.11803342130469505),
 (4000, 0.11803342130469505),
 (160, 0.11712303424679457),
 (182, 0.11707322644771176),
 (278, 0.11707322644771176),
 (2284, 0.11707322644771176),
 (28, 0.116543309349613),
 (422, 0.116543309349613),
 (678, 0.116543309349613),
 (589, 0.1163350101494222),
 (454, 0.11587244366483038),
 (2547, 0.11587244366483038),
 (1497, 0.11551284429847784),
 (3212, 0.11506355109724453),
 (189, 0.1147078669352809),
 (1220, 0.1147078669352809),
 (236, 0.11470786693528087),
 (85, 0.1141270638770543),
 (432, 0.11357771260606365),
 (1418, 0.11357771260606365),
 (50, 0.11295649894498103),
 (1616, 0.11295649894498103),
 (420, 0.1124803176664619),
 (536, 0.1124803176664619),
 (2372, 0.1124803176664619),
 (889, 0.11243619908556624),
 (3147, 0.11239029738980327),
 (256, 0.11164843913471803),
 (808, 0.11164843913471803),
 (1348, 0.11164843913471803),
 (3309, 0.11141412945539662),
 (1512, 0.11141412945539661),
 (87, 0.11128297681493143),
 (121, 0.11128297681493143),
 (232, 0.11128297681493143),
 (4468, 0.11128297681493143),
 (206, 0.11092107999698035),
 (238, 0.11092107999698035),
 (228, 0.11037769642208699),
 (81, 0.11020775375559676),
 (1574, 0.11020775375559674),
 (3428, 0.10968169942141637),
 (21, 0.10968169942141635),
 (449, 0.10968169942141635),
 (1031, 0.10968169942141635),
 (1945, 0.10968169942141635),
 (3008, 0.10968169942141635),
 (123, 0.10936965981495178),
 (692, 0.10936965981495178),
 (200, 0.10882143751650175),
 (627, 0.10882143751650175),
 (653, 0.10882143751650175),
 (1501, 0.10882143751650175),
 (1524, 0.10882143751650175),
 (1575, 0.10882143751650175),
 (307, 0.10876595882948199),
 (5, 0.10838874619051501),
 (740, 0.10838874619051501),
 (3093, 0.10838874619051501),
 (3630, 0.10838874619051501),
 (786, 0.10814761408717502),
 (3498, 0.10814761408717502),
 (4777, 0.10814761408717502),
 (229, 0.1074861545850028),
 (572, 0.10743376064838502),
 (939, 0.1068366854693644),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (1237, 0.106676149412533),
 (170, 0.10650358071057624),
 (262, 0.10650358071057624),
 (1166, 0.10619884881071831),
 (1745, 0.10619884881071831),
 (2161, 0.10619884881071831),
 (2634, 0.10619884881071831),
 (4135, 0.10619884881071831),
 (467, 0.10559715077387793),
 (541, 0.10559715077387793),
 (1496, 0.10559715077387793),
 (131, 0.10526315789473685),
 (295, 0.10526315789473685),
 (814, 0.10526315789473685),
 (2072, 0.10526315789473685),
 (3340, 0.10526315789473685),
 (2498, 0.10471347707292386),
 (75, 0.10390486669322622),
 (223, 0.10390486669322622),
 (687, 0.10390486669322622),
 (1195, 0.10390486669322622),
 (1771, 0.10390486669322622),
 (2148, 0.10390486669322622),
 (2817, 0.10390486669322622),
 (654, 0.10385162309931599),
 (2439, 0.10385162309931599),
 (105, 0.1037571695799112),
 (233, 0.1037571695799112),
 (2323, 0.1037571695799112),
 (2456, 0.1037571695799112),
 (2521, 0.1037571695799112),
 (3055, 0.1037571695799112),
 (3621, 0.1037571695799112),
 (3839, 0.1037571695799112),
 (1455, 0.10301070542879115),
 (10, 0.10259783520851541),
 (1082, 0.10259783520851541),
 (3152, 0.10259783520851541),
 (3634, 0.10259783520851541),
 (3755, 0.10259783520851541),
 (3874, 0.10259783520851541),
 (4097, 0.10259783520851541),
 (2106, 0.10218988991416095),
 (624, 0.10147651372376076),
 (2762, 0.10147651372376076),
 (3663, 0.10147651372376076),
 (3954, 0.10147651372376076),
 (3441, 0.10138838820672659),
 (508, 0.101338918387628),
 (1294, 0.101338918387628),
 (2247, 0.10133891838762799),
 (1405, 0.10060545457319173),
 (1439, 0.10060545457319173),
 (2099, 0.10060545457319173),
 (312, 0.10012523486435178),
 (330, 0.10012523486435178),
 (643, 0.10012523486435178),
 (988, 0.10012523486435178),
 (1037, 0.10012523486435178),
 (1614, 0.10012523486435178),
 (35, 0.09933992677987831),
 (157, 0.09933992677987831),
 (319, 0.09933992677987831),
 (325, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1077, 0.09933992677987831),
 (1280, 0.09933992677987831),
 (1884, 0.09933992677987831),
 (2053, 0.09933992677987831),
 (4018, 0.09933992677987831),
 (4198, 0.09933992677987831),
 (4490, 0.09933992677987831),
 (363, 0.09909250441117726),
 (491, 0.09909250441117726),
 (266, 0.0989541391990587),
 (445, 0.0989541391990587),
 (510, 0.0989541391990587),
 (3620, 0.0989541391990587),
 (3783, 0.0989541391990587),
 (3935, 0.0989541391990587),
 (1775, 0.09836118442057921),
 (410, 0.0978231976089037),
 (480, 0.0978231976089037),
 (535, 0.0978231976089037),
 (898, 0.0978231976089037),
 (1109, 0.0978231976089037),
 (1401, 0.0978231976089037),
 (1823, 0.0978231976089037),
 (2253, 0.0978231976089037),
 (33, 0.09733285267845754),
 (148, 0.09733285267845754),
 (263, 0.09733285267845754),
 (791, 0.09733285267845754),
 (878, 0.09733285267845754),
 (1156, 0.09733285267845754),
 (1727, 0.09733285267845754),
 (1942, 0.09733285267845754),
 (2787, 0.09733285267845754),
 (4256, 0.09733285267845754),
 (4403, 0.09733285267845754),
 (4472, 0.09733285267845754),
 (9, 0.0967301666813349),
 (334, 0.0967301666813349),
 (371, 0.09567297464698798),
 (412, 0.09567297464698798),
 (2241, 0.09567297464698798),
 (2556, 0.09567297464698798),
 (4545, 0.09558988911273408),
 (362, 0.09544271444636668),
 (2562, 0.09544271444636668),
 (4203, 0.09544271444636668),
 (18, 0.09493290614465533),
 (11, 0.09464970485606021),
 (587, 0.09464970485606021),
 (2650, 0.09464970485606021),
 (660, 0.09365858115816941),
 (920, 0.09365858115816941),
 (1276, 0.09365858115816941),
 (1357, 0.09365858115816941),
 (1474, 0.09365858115816941),
 (1573, 0.09365858115816941),
 (1686, 0.09365858115816941),
 (1692, 0.09365858115816941),
 (1721, 0.09365858115816941),
 (2396, 0.09365858115816941),
 (2488, 0.09365858115816941),
 (2592, 0.09365858115816941),
 (2645, 0.09365858115816941),
 (2820, 0.09365858115816941),
 (3537, 0.09365858115816941),
 (3720, 0.09365858115816941),
 (4331, 0.09365858115816941),
 (4502, 0.09365858115816941),
 (129, 0.09269795493186431),
 (243, 0.09269795493186431),
 (279, 0.09269795493186431),
 (473, 0.09269795493186431),
 (596, 0.09269795493186431),
 (813, 0.09269795493186431),
 (1446, 0.09269795493186431),
 (1701, 0.09269795493186431),
 (3407, 0.09269795493186431),
 (301, 0.09243423333081696),
 (785, 0.09243423333081695),
 (219, 0.09197090092274487),
 (244, 0.09197090092274487),
 (511, 0.09197090092274487),
 (980, 0.09197090092274487),
 (1756, 0.09197090092274487),
 (2093, 0.09197090092274487),
 (2651, 0.09197090092274487),
 (3736, 0.09197090092274487),
 (230, 0.09183979479633063),
 (799, 0.09183979479633063),
 (2570, 0.09183979479633061),
 (239, 0.09125667909262308),
 (43, 0.09086217008485092),
 (602, 0.09086217008485092),
 (997, 0.09086217008485092),
 (1233, 0.09086217008485092),
 (1846, 0.09086217008485092),
 (3881, 0.09086217008485092),
 (12, 0.09037128496931669),
 (88, 0.09037128496931669),
 (167, 0.09037128496931669),
 (356, 0.09037128496931669),
 (400, 0.09037128496931669),
 (1306, 0.09037128496931669),
 (1480, 0.09037128496931669),
 (2251, 0.09037128496931669),
 (2957, 0.09037128496931669),
 (331, 0.08998425413316952),
 (2363, 0.08998425413316952),
 (2796, 0.08998425413316952),
 (2856, 0.08998425413316952),
 (3389, 0.08998425413316952),
 (3443, 0.08998425413316952),
 (3462, 0.08998425413316952),
 (4343, 0.08998425413316952),
 (4353, 0.08998425413316952),
 (274, 0.08977310580745099),
 (1906, 0.0891313035643173),
 (2115, 0.08903057122447033),
 (292, 0.08885233166386385),
 (564, 0.08885233166386385),
 (1027, 0.08885233166386385),
 (2660, 0.08885233166386385),
 (2868, 0.08885233166386385),
 (3322, 0.08885233166386385),
 (169, 0.08830215713766959),
 (270, 0.08830215713766959),
 (618, 0.08830215713766959),
 (1783, 0.08830215713766959),
 (2109, 0.08830215713766959),
 (2713, 0.08830215713766959),
 (2740, 0.08830215713766959),
 (3553, 0.08830215713766959),
 (479, 0.08797691788472335),
 (752, 0.08749572785196143),
 (1832, 0.08749572785196143),
 (3556, 0.08749572785196143),
 (2448, 0.08746392856766495),
 (23, 0.08740748201220976),
 (141, 0.08740748201220976),
 (389, 0.08740748201220976),
 (745, 0.08740748201220976),
 (794, 0.08740748201220976),
 (960, 0.08740748201220976),
 (1249, 0.08740748201220976),
 (1259, 0.08740748201220976),
 (3448, 0.08740748201220976),
 (3449, 0.08740748201220976),
 (143, 0.08671099695241201),
 (199, 0.08671099695241201),
 (827, 0.08671099695241201),
 (1019, 0.08671099695241201),
 (1530, 0.08671099695241201),
 (2880, 0.08671099695241201),
 (4516, 0.08671099695241201),
 (4587, 0.08671099695241201),
 (2, 0.08603090020146065),
 (457, 0.08603090020146065),
 (775, 0.08603090020146065),
 (1378, 0.08603090020146065),
 (2583, 0.08603090020146065),
 (3135, 0.08603090020146065),
 (4754, 0.08603090020146065),
 (234, 0.08594700851870801),
 (2354, 0.08594700851870801),
 (32, 0.08520286456846099),
 (190, 0.08520286456846099),
 (217, 0.08520286456846099),
 (2968, 0.08520286456846099),
 (142, 0.08471737420873576),
 (894, 0.08471737420873576),
 (1097, 0.08471737420873576),
 (1142, 0.08471737420873576),
 (1589, 0.08471737420873576),
 (2304, 0.08471737420873576),
 (4560, 0.08471737420873576),
 (48, 0.08447772061910234),
 (1305, 0.08447772061910234),
 (1639, 0.08447772061910234),
 (62, 0.0837707816583391),
 (381, 0.0837707816583391),
 (534, 0.0837707816583391),
 (1698, 0.0837707816583391),
 (3180, 0.0837707816583391),
 (3218, 0.0837707816583391),
 (3978, 0.0837707816583391),
 (4737, 0.0837707816583391),
 (1, 0.08346223261119858),
 (152, 0.08346223261119858),
 (203, 0.08346223261119858),
 (315, 0.08346223261119858),
 (547, 0.08346223261119858),
 (1688, 0.08346223261119858),
 (1749, 0.08346223261119858),
 (2128, 0.08346223261119858),
 (2386, 0.08321783316232578),
 (19, 0.0830812984794528),
 (403, 0.0830812984794528),
 (3905, 0.0830812984794528),
 (2203, 0.08240856434303293),
 (39, 0.08226127456606226),
 (227, 0.08226127456606226),
 (341, 0.08226127456606226),
 (626, 0.08226127456606226),
 (787, 0.08226127456606226),
 (1207, 0.08226127456606226),
 (2167, 0.08226127456606226),
 (2661, 0.08226127456606226),
 (3140, 0.08226127456606226),
 (3301, 0.08226127456606226),
 (3470, 0.08226127456606226),
 (45, 0.08175191193132876),
 (63, 0.08175191193132876),
 (501, 0.08175191193132876),
 (38, 0.08111071056538127),
 (242, 0.08111071056538127),
 (245, 0.08111071056538127),
 (306, 0.08111071056538127),
 (584, 0.08111071056538127),
 (812, 0.08111071056538127),
 (866, 0.08111071056538127),
 (901, 0.08111071056538127),
 (1519, 0.08111071056538127),
 (1664, 0.08111071056538127),
 (2339, 0.08111071056538127),
 (2644, 0.08111071056538127),
 (2671, 0.08111071056538127),
 (2865, 0.08111071056538127),
 (2877, 0.08111071056538127),
 (3527, 0.08111071056538127),
 (3926, 0.08111071056538127),
 (4492, 0.08111071056538127),
 (4568, 0.08111071056538127),
 (4626, 0.08111071056538127),
 (4641, 0.08111071056538127),
 (4654, 0.08111071056538127),
 (4657, 0.08111071056538127),
 (103, 0.08048436365855338),
 (2792, 0.08048436365855338),
 (164, 0.08000711205939975),
 (854, 0.08000711205939975),
 (899, 0.08000711205939975),
 (1269, 0.08000711205939975),
 (1325, 0.08000711205939975),
 (1747, 0.08000711205939975),
 (2683, 0.08000711205939975),
 (3764, 0.08000711205939975),
 (3816, 0.08000711205939975),
 (3851, 0.08000711205939975),
 (486, 0.07992075789278004),
 (51, 0.07987230638308718),
 (222, 0.07987230638308718),
 (1534, 0.07987230638308718),
 (4506, 0.07987230638308718),
 (1898, 0.0792740035289418),
 (16, 0.07894736842105264),
 (37, 0.07894736842105264),
 (241, 0.07894736842105264),
 (329, 0.07894736842105264),
 (1080, 0.07894736842105264),
 (1161, 0.07894736842105264),
 (2295, 0.07894736842105264),
 (3233, 0.07894736842105264),
 (4316, 0.07894736842105264),
 (193, 0.07878168645790681),
 (153, 0.07868894753646337),
 (776, 0.07868894753646337),
 (1045, 0.07868894753646337),
 (1139, 0.07868894753646337),
 (1828, 0.07868894753646337),
 (1926, 0.07868894753646337),
 (3728, 0.07868894753646337),
 (3832, 0.07868894753646337),
 (4279, 0.07868894753646337),
 (286, 0.0781166566864507),
 (1659, 0.0781166566864507),
 (174, 0.07792865001991967),
 (402, 0.07792865001991967),
 (922, 0.07792865001991967),
 (1113, 0.07792865001991967),
 (2938, 0.07792865001991967),
 (3028, 0.07792865001991967),
 (3091, 0.07792865001991967),
 (3102, 0.07792865001991967),
 (3164, 0.07792865001991967),
 (4341, 0.07792865001991967),
 (1924, 0.07755667343294813),
 (3560, 0.07755667343294813),
 (1282, 0.0770085628656519),
 (40, 0.07694837640638656),
 (96, 0.07694837640638656),
 (101, 0.07694837640638656),
 (112, 0.07694837640638656),
 (207, 0.07694837640638656),
 (632, 0.07694837640638656),
 (737, 0.07694837640638656),
 (1289, 0.07694837640638656),
 (2219, 0.07694837640638656),
 (4268, 0.07694837640638656),
 (4624, 0.07694837640638656),
 (850, 0.07647191129018727),
 (1005, 0.07647191129018727),
 (1254, 0.07647191129018727),
 (1621, 0.07647191129018727),
 (2165, 0.07647191129018727),
 (2274, 0.07647191129018727),
 (2712, 0.07647191129018727),
 (3430, 0.07647191129018727),
 (4165, 0.07647191129018727),
 (4473, 0.07647191129018727),
 (70, 0.076004188790721),
 (82, 0.076004188790721),
 (235, 0.076004188790721),
 (349, 0.076004188790721),
 (492, 0.076004188790721),
 (1290, 0.076004188790721),
 (1523, 0.076004188790721),
 (2449, 0.076004188790721),
 (2916, 0.076004188790721),
 (4045, 0.076004188790721),
 (4558, 0.076004188790721),
 (246, 0.07594632491572426),
 (125, 0.07577352304240824),
 (2005, 0.07543142864047142),
 (3331, 0.07530940414109724),
 (98, 0.07509392614826384),
 (210, 0.07509392614826384),
 (361, 0.07509392614826384),
 (365, 0.07509392614826384),
 (503, 0.07509392614826384),
 (540, 0.07509392614826384),
 (680, 0.07509392614826384),
 (1009, 0.07509392614826384),
 (1293, 0.07509392614826384),
 (2163, 0.07509392614826384),
 (4205, 0.07509392614826384),
 (2256, 0.07492686492653551),
 (205, 0.07443229275647868),
 (800, 0.07443229275647868),
 (995, 0.07443229275647868),
 (1323, 0.07443229275647868),
 (1521, 0.07443229275647868),
 (1770, 0.07443229275647868),
 (2326, 0.07443229275647868),
 (2551, 0.07443229275647868),
 (2801, 0.07443229275647868),
 (3069, 0.07443229275647868),
 (3117, 0.07443229275647868),
 (3126, 0.07443229275647868),
 (4011, 0.07443229275647868),
 (4412, 0.07443229275647868),
 (4542, 0.07443229275647868),

In [68]:
def recommend(movie):
    movie_index = new_df[new_df["title"] == movie].index[0]
    print(movie_index)
    distance = similarity[movie_index]
    print(distance)
    movie_list = sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])
    
    for i in movie_list[1:6]:
        print(new_df.iloc[i[0]].title)

In [69]:
recommend("Avatar")

0
[1.         0.08346223 0.0860309  ... 0.04499213 0.         0.        ]
Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [70]:
2+2

4

In [71]:
import pickle

In [72]:
pickle.dump(new_df,open("movies.pkl","wb"))

In [73]:
new_df

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [74]:
pd.__version__

'1.3.4'

In [76]:
pickle.dump(similarity,open("similarity.pkl",'wb'))